In [4]:
import pandas as pd

In [7]:
data = pd.read_csv("../output/dataset_patients.csv.gz")
data.head(3)

,patient_id,start_date,index_date,registered_start,registered_index,alive,sex,age,date_of_birth,imd,...,recurrent_uti_12m,recurrent_uti,include_patient_otitis_media,include_patient_sinusitis,include_patient_sore_throat,include_patient_insect_bites,include_patient_shingles,include_patient_impetigo,include_patient_uuti,include_patient_overall_eligible
0,1,2025-10-01,2025-11-01,T,T,T,unknown,92,1933-10-01,Missing,...,F,F,F,T,T,T,T,T,F,T
1,2,2025-10-01,2025-11-01,T,T,T,female,96,1929-11-01,Missing,...,F,F,F,T,T,T,T,T,F,T
2,3,2025-10-01,2025-11-01,T,T,T,intersex,64,1961-06-01,Missing,...,F,F,F,T,T,T,T,T,F,T

In [5]:
df = pd.read_csv("../output/dataset_patients_2024-02-01.csv.gz")
df.head(3)

,patient_id,start_date,index_date,registered_start,registered_index,alive,sex,age,date_of_birth,imd,...,recurrent_uti_12m,recurrent_uti,include_patient_otitis_media,include_patient_sinusitis,include_patient_sore_throat,include_patient_insect_bites,include_patient_shingles,include_patient_impetigo,include_patient_uuti,include_patient_overall_eligible
0,1,2024-02-01,2024-03-01,T,T,T,unknown,90,1933-10-01,Missing,...,F,F,F,T,T,T,T,T,F,T
1,2,2024-02-01,2024-03-01,T,T,T,female,94,1929-11-01,3,...,F,F,F,T,T,T,T,T,F,T
2,3,2024-02-01,2024-03-01,T,T,T,intersex,62,1961-06-01,Missing,...,F,F,F,T,T,T,T,T,F,T

In [6]:
df2 = pd.read_csv("../output/dataset_patients_2024-03-01.csv.gz")
df2.head(3)

,patient_id,start_date,index_date,registered_start,registered_index,alive,sex,age,date_of_birth,imd,...,recurrent_uti_12m,recurrent_uti,include_patient_otitis_media,include_patient_sinusitis,include_patient_sore_throat,include_patient_insect_bites,include_patient_shingles,include_patient_impetigo,include_patient_uuti,include_patient_overall_eligible
0,1,2024-03-01,2024-04-01,T,T,T,unknown,90,1933-10-01,Missing,...,F,F,F,T,T,T,T,T,F,T
1,2,2024-03-01,2024-04-01,T,T,T,female,94,1929-11-01,3,...,F,F,F,T,T,T,T,T,F,T
2,3,2024-03-01,2024-04-01,T,T,T,intersex,62,1961-06-01,Missing,...,F,F,F,T,T,T,T,T,F,T

Question: why patient_id 9 - age 58 -> 61?